spring:
  datasource:
    url: jdbc:h2:mem:products
    driverClassName: org.h2.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: none   # let SQL scripts handle schema
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always   # important! ensures scripts run for embedded DB
      schema-locations: classpath:data.sql
      data-locations: classpath:data.sql   # if using same file
server:
  port: 8181

application:
  jwk-set-uri: ${JWK_SET_URI:http://localhost:9000/oauth2/jwks}

