services:
  authorization-server:
    container_name: authorization-server
    image: rupesh1997/authorization-server:1.0.0
    ports:
      - "9000:9000"
    extends:
      file: common-config.yaml
      service: network-configuration

  resource-server:
    container_name: resource-server
    image: rupesh1997/resource-server:1.0.0
    depends_on:
      authorization-server:
        condition: service_started
    ports:
      - "8181:8181"
    environment:
      JWK_SET_URI: http://authorization-server:9000/oauth2/jwks
    extends:
      file: common-config.yaml
      service: network-configuration

  frontend:
    container_name: frontend
    image: rupesh1997/frontend:1.0.0
    depends_on:
      authorization-server:
        condition: service_started
      resource-server:
        condition: service_started
    ports:
      - "8080:8080"
    extends:
      file: common-config.yaml
      service: network-configuration

networks:
  oauth-network:
    driver: 'bridge'



  # docker system prune -f
  # docker compose -f docker/docker-compose/docker-compose.yaml down
  # docker compose -f docker/docker-compose/docker-compose.yaml up -d
  # docker logs <container-id>
  # cat ~/.ssh/id_rsa

  # docker exec -it frontend sh
  # curl http://authorization-server:9000/.well-known/openid-configuration