spring:
  config:
    activate:
      on-profile: "production"

  security:
    oauth2:
      authorizationserver:
        issuer: http://${application.url}:9000

application:
  url: 192.168.1.70
  cors:
    endpoints: http://${application.url}:8081