spring:
  config:
    activate:
      on-profile: "production"

  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000

application:
  cors:
    endpoints: http://192.168.1.70:8081,http://192.168.1.70:8181,http://192.168.1.70:3000
