spring:
  config:
    activate:
      on-profile: "production"

  security:
    oauth2:
      authorizationserver:
        issuer: https://${application.url}:9000  # Use HTTPS in production

application:
  url: 192.168.1.70
  cors:
    endpoints: https://${application.url}:8081