name: authorization server pipeline

on:
  push:
    branches: [ main ]
    paths:
      - authorization-server-application/**
      - docker/backend/authorization-server/Dockerfile
      - docker/docker-compose/docker-compose.yaml
      - docker/docker-compose/common-config.yaml
      - .github/workflows/authorization-server-pipeline.yaml

env:
  PROJECT_NAME: authorization-server

jobs:

  compile:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Compile
        run: |
          cd authorization-server-application
          ./mvnw clean compile

  unit-tests:
    runs-on: self-hosted
    needs: compile
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Unit tests
        run: |
          cd authorization-server-application
          ./mvnw test

  build:
    runs-on: self-hosted
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-

      - name: Build JAR
        run: |
          cd authorization-server-application
          ./mvnw clean package -DskipTests

  docker:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        id: extract_version
        run: |
          cd authorization-server-application
          echo "VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET_KEY }}

      - uses: docker/setup-buildx-action@v3

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: authorization-server-application
          file: docker/backend/authorization-server/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/authorization-server:${{ steps.extract_version.outputs.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/authorization-server:latest
          build-args: |
            JAR_VERSION=${{ steps.extract_version.outputs.VERSION }} 
            ACTIVE_PROFILE=default

  deployment:
    runs-on: self-hosted
    needs: docker
    steps:

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy compose files
        run: |
          scp docker/docker-compose/docker-compose.yaml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:deployment/docker-compose.yaml
          scp docker/docker-compose/common-config.yaml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:deployment/common-config.yaml

      - name: Deploy
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "
            mkdir -p deployment &&
            cd deployment &&
            docker system prune -f &&
            docker compose -p authorization-server -f docker-compose.yaml down &&
            docker compose -p authorization-server -f docker-compose.yaml pull -q &&
            docker compose -p authorization-server -f docker-compose.yaml up -d
          "
