name: authorization server pipeline

on:
  push:
    branches: [ main ]
    paths:
      - authorization-server-application/**
      - docker/backend/authorization-server/Dockerfile
      - .github/workflows/authorization-server-pipeline.yaml

env:
  PROJECT_NAME: authorization-server

jobs:

  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto

      - name: Compile
        run: |
          cd authorization-server-application
          ./mvnw clean compile

      - name: Unit tests
        run: |
          cd authorization-server-application
          ./mvnw test

      - name: Build JAR
        run: |
          cd authorization-server-application
          ./mvnw clean package -DskipTests

  docker:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        id: extract_version
        run: |
          cd authorization-server-application
          echo "VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET_KEY }}

      - uses: docker/setup-buildx-action@v3

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: authorization-server-application  # Path to your app context
          file: docker/backend/authorization-server/Dockerfile  # Path to your Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/authorization-server:${{ steps.extract_version.outputs.VERSION }} 
            ${{ secrets.DOCKERHUB_USERNAME }}/authorization-server:latest
          build-args: |
            APP_VERSION=${{ steps.extract_version.outputs.VERSION }} 
            ACTIVE_PROFILE=production

  update-docker-compose:
    name: Update Docker Compose with new version
    runs-on: ubuntu-latest
    needs: [ docker ]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Setup Git config
        run: |
          git config user.name "Rupesh1997"
          git config user.email "dulalrupesh77@gmail.com"

      - name: Update docker-compose.yaml with new version
        env:
          IMAGE_TAG: ${{ steps.extract_version.outputs.VERSION }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          REGISTRY: ghcr.io
        run: |
          NEW_IMAGE="${REGISTRY}/${GITHUB_REPOSITORY}/authorization-server:${IMAGE_TAG}"
          
          # Replace ONLY the image value in docker-compose file (and preserve indentation)
          sed -i "s|\(image:\s*\).*|\1${NEW_IMAGE}|g" docker/docker-compose/production/docker-compose.yaml
          
          echo "Updated docker-compose to use image: ${NEW_IMAGE}"
          grep -A 2 "image:" docker/docker-compose/production/docker-compose.yaml

      - name: Commit and push changes
        run: |
          # Check if there are any changes in the docker-compose.yaml before committing
          if git diff --exit-code docker/docker-compose/production/docker-compose.yaml; then
            echo "No changes to commit"
          else
            git add docker/docker-compose/production/docker-compose.yaml
            git commit -m "Update docker-compose with new image tag: ${IMAGE_TAG} [skip ci]"
            git push

      - name: Ignore changes to docker-compose and common config
        run: |
          echo "No need to trigger workflow for changes in docker-compose files and common-config.yaml."
        if: github.event.head_commit.message == 'Update docker-compose with new image tag'

  deployment:
    name: Deployment
    runs-on: self-hosted
    needs: [ update-docker-compose ]
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create deployment folder
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "mkdir -p deployment"

      - name: Copy docker compose and common config files
        run: |
          scp docker/docker-compose/production/docker-compose.yaml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:deployment/docker-compose.yaml
          scp docker/docker-compose/production/common-config.yaml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:deployment/common-config.yaml

      - name: Setup environment variables
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} <<EOF
          cd deployment
          docker system prune -f
          docker-compose -f docker-compose.yaml down
          docker-compose -f docker-compose.yaml pull -q
          docker-compose -f docker-compose.yaml up -d
          EOF
