name: frontend pipeline

on:
  push:
    branches:
      - main
    paths:
      - frontend/**
      - docker/frontend/Dockerfile
      - docker/docker-compose/docker-compose.yaml
      - docker/docker-compose/common-config.yaml
      - .github/workflows/frontend-pipeline.yaml

jobs:
  build-image:
    name: Build frontend docker image
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      # Safe npm cache â€” speeds up build but never breaks pipeline
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-cache-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            npm-cache-

      - name: Extract version from package.json
        id: extract_version
        run: |
          cd frontend
          echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_OUTPUT

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET_KEY }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v5
        with:
          context: frontend
          file: docker/frontend/Dockerfile
          push: true
          platforms: linux/amd64
          pull: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ steps.extract_version.outputs.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
          build-args: |
            CONFIGURATION=production


  deploy:
    name: Deploy Frontend
    runs-on: self-hosted
    needs: [ build-image ]

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Upload docker-compose file
        run: |
          scp docker/docker-compose/docker-compose.yaml \
              ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:deployment/docker-compose.yaml

      - name: Deploy frontend container
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "
            mkdir -p deployment &&
            cd deployment &&
            docker system prune -f &&
            docker compose -f docker-compose.yaml down &&
            docker compose -f docker-compose.yaml pull -q &&
            docker compose -f docker-compose.yaml up -d
          "