name: resource server pipeline

on:
  push:
    branches:
      - main
    paths:
      - resource-server-application/**
      - docker/backend/resource-server/Dockerfile
      - docker/docker-compose/docker-compose.yaml
      - docker/docker-compose/common-config.yaml
      - .github/workflows/resource-server-pipeline.yaml

jobs:
  compile:
    runs-on: self-hosted
    name: Compile project
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto

      - name: Compile project
        run: |
          cd resource-server-application
          ./mvnw clean compile

  unit-tests:
    runs-on: self-hosted
    name: Unit tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto

      - name: Unit tests
        run: |
          cd resource-server-application
          ./mvnw clean test

  build:
    runs-on: self-hosted
    name: Build project
    needs: [ compile, unit-tests ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto

      - name: Unit tests
        run: |
          cd resource-server-application
          ./mvnw clean package -DskipTests

  docker:
    runs-on: self-hosted
    name: Build and push docker image
    needs: [ build ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: Build project
        run: |
          cd resource-server-application
          ./mvnw clean package -DskipTests

      - name: Extract project version
        id: extract_version
        run: |
          cd resource-server-application
          echo "VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET_KEY }}

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: resource-server-application
          file: docker/backend/resource-server/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/course-management-system:${{ steps.extract_version.outputs.VERSION }},${{ secrets.DOCKERHUB_USERNAME }}/course-management-system:latest
          build-args: |
            PROFILE=default
            APP_VERSION=${{ steps.extract_version.outputs.VERSION }}

  deployment:
    name: Deploy resource server
    runs-on: self-hosted
    needs: [ docker ]
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Create deployment folder
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "mkdir -p deployment"

      - name: Copy docker compose and common config files
        run: |
          scp docker/docker-compose/docker-compose.yaml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:deployment/docker-compose.yaml
          scp docker/docker-compose/common-config.yaml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:deployment/common-config.yaml

      - name: Setup environment variables
        run: |
          ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} <<EOF
          cd deployment
          docker-compose -f docker-compose.yaml down
          docker-compose -f docker-compose.yaml pull -q
          docker-compose -f docker-compose.yaml up -d
          EOF

