name: resource server pipeline

on:
  push:
    branches:
      - main
    paths:
      - resource-server-application/**
      - docker/backend/resource-server/Dockerfile
      - .github/workflows/resource-server-pipeline.yaml
    paths-ignore:
      - docker/docker-compose/production/docker-compose.yaml
      - docker/docker-compose/production/common-config.yaml

jobs:
  build:
    runs-on: self-hosted
    name: Compile project
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: corretto

      - name: Compile
        run: |
          cd resource-server-application
          ./mvnw clean compile

      - name: Run unit tests
        run: |
          cd resource-server-application
          ./mvnw test

      - name: Build project
        run: |
          cd resource-server-application
          ./mvnw clean package -DskipTests

  docker:
    runs-on: self-hosted
    name: Build and push docker image
    needs: [ build ]
    steps:
      - uses: actions/checkout@v4

      - name: Extract project version
        id: extract_version
        run: |
          cd resource-server-application
          echo "VERSION=$(./mvnw -q -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_OUTPUT

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET_KEY }}

      - uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v5
        with:
          context: resource-server-application
          file: docker/backend/resource-server/Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/resource-server:${{ steps.extract_version.outputs.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/resource-server:latest
          build-args: |
            APP_VERSION=${{ steps.extract_version.outputs.VERSION }} 
            ACTIVE_PROFILE=default

  update-docker-compose:
    name: Update Docker Compose with new version
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Setup Git config
        run: |
          git config user.name "Rupesh1997"
          git config user.email "dulalrupesh77@gmail.com"

      - name: Update docker-compose.yaml with new version
        env:
          IMAGE_TAG: ${{ steps.extract_version.outputs.VERSION }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          REGISTRY: ghcr.io
        run: |
          NEW_IMAGE="${REGISTRY}/${GITHUB_REPOSITORY}/resource-server:${IMAGE_TAG}"

          # Replace ONLY the image value in docker-compose file (and preserve indentation)
          sed -i "s|\(image:\s*\).*|\1${NEW_IMAGE}|g" docker/docker-compose/production/docker-compose.yaml

          echo "Updated docker-compose to use image: ${NEW_IMAGE}"
          grep -A 2 "image:" docker/docker-compose/production/docker-compose.yaml

      - name: Commit and push changes
        run: |
          # Check if there are any changes in the docker-compose.yaml before committing
          if git diff --exit-code docker/docker-compose/production/docker-compose.yaml; then
            echo "No changes to commit"
          else
            git add docker/docker-compose/production/docker-compose.yaml
            git commit -m "Update docker-compose with new image tag: ${IMAGE_TAG} [skip ci]"
            git push

      - name: Ignore changes to docker-compose and common config
        run: |
          echo "No need to trigger workflow for changes in docker-compose files and common-config.yaml."
        if: github.event.head_commit.message == 'Update docker-compose with new image tag'