services:

  authorization-server:
    container_name: authorization-server
    image: rupesh1997/authorization-server:latest
    ports:
      - "9000:9000"
    environment:
      SPRING_PROFILES_ACTIVE: production
      SECURITY_OAUTH2_AUTHORIZATIONSERVER_ISSUER: http://192.168.1.70:9000
    extends:
      file: common-config.yaml
      service: network-configuration

  resource-server:
    container_name: resource-server
    image: rupesh1997/resource-server:1.0.0
    depends_on:
      authorization-server:
        condition: service_started
    ports:
      - "8181:8181"
    environment:
      JWK_SET_URI: http://192.168.1.70:9000/oauth2/jwks
    extends:
      file: common-config.yaml
      service: network-configuration

  frontend:
    container_name: frontend
    image: rupesh1997/frontend:1.0.0
    depends_on:
      authorization-server:
        condition: service_started
      resource-server:
        condition: service_started
    ports:
      - "8081:8080"
    extends:
      file: common-config.yaml
      service: network-configuration

networks:
  ums-network:
    driver: 'bridge'